-- =====================================================================
-- AAhAT MESSAGING PLATFORM — PRODUCTION SQL SCHEMA
-- Target Database: Supabase PostgreSQL
-- Features: Real-time, RLS Policies, Query Indexes, E2EE Support
-- =====================================================================

-- -------------------------------------------------------------
-- 1. CLEANUP (Optional - Use with caution in live databases)
-- -------------------------------------------------------------
-- DROP TABLE IF EXISTS messages;
-- DROP TABLE IF EXISTS contacts;
-- DROP TABLE IF EXISTS users;

-- -------------------------------------------------------------
-- 2. TABLE DEFINITIONS
-- -------------------------------------------------------------

-- Users table (Offline/Client Auth Sync & Session Control)
CREATE TABLE IF NOT EXISTS users (
    email TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "isSessionActive" BOOLEAN DEFAULT false NOT NULL,
    "fcmToken" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Contacts / Conversations table
CREATE TABLE IF NOT EXISTS contacts (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    "avatarUrl" TEXT,
    "isActive" BOOLEAN DEFAULT false NOT NULL,
    "lastActiveText" TEXT DEFAULT 'Offline' NOT NULL,
    "isRecent" BOOLEAN DEFAULT false NOT NULL,
    "recentMessageText" TEXT DEFAULT '' NOT NULL,
    "recentMessageTime" TEXT DEFAULT '' NOT NULL,
    "recentMessageIsUnread" BOOLEAN DEFAULT false NOT NULL,
    "isGroup" BOOLEAN DEFAULT false NOT NULL,
    "isArchived" BOOLEAN DEFAULT false NOT NULL,
    "isFavorite" BOOLEAN DEFAULT false NOT NULL,
    "isMuted" BOOLEAN DEFAULT false NOT NULL,
    "isPinned" BOOLEAN DEFAULT false NOT NULL,
    "memberCount" INT DEFAULT 0 NOT NULL,
    "description" TEXT,
    "unreadCount" INT DEFAULT 0 NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Messages table
CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "contactId" TEXT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    "isFromMe" BOOLEAN NOT NULL,
    timestamp BIGINT NOT NULL,
    "timeText" TEXT NOT NULL,
    "isRead" BOOLEAN DEFAULT false NOT NULL,
    "attachmentUrl" TEXT,
    reaction TEXT,
    "replyToId" BIGINT,
    "replyToText" TEXT,
    "replyToSender" TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- -------------------------------------------------------------
-- 3. PERFORMANCE INDEXES
-- -------------------------------------------------------------

-- Index for fetching chat messages sorted by timestamp inside a conversation (most common query)
CREATE INDEX IF NOT EXISTS idx_messages_contact_timestamp 
ON messages ("contactId", timestamp DESC);

-- Index for scanning unread messages in conversations
CREATE INDEX IF NOT EXISTS idx_messages_unread 
ON messages ("contactId", "isRead") 
WHERE "isRead" = false;

-- Index for filtering contacts by categories (Favorites, Archived, Groups)
CREATE INDEX IF NOT EXISTS idx_contacts_categories 
ON contacts ("isGroup", "isArchived", "isFavorite");

-- -------------------------------------------------------------
-- 4. REAL-TIME SUBSCRIPTION SERVICES
-- -------------------------------------------------------------

-- Enable real-time updates for messages and contacts
DO $$
BEGIN
  -- Create publication if not exists
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;

  -- Add messages table if not already added
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    WHERE c.relname = 'messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE messages;
  END IF;

  -- Add contacts table if not already added
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_rel pr 
    JOIN pg_class c ON pr.prrelid = c.oid 
    WHERE c.relname = 'contacts'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE contacts;
  END IF;
END $$;

-- -------------------------------------------------------------
-- 5. SECURITY & ROW-LEVEL SECURITY (RLS) POLICIES
-- -------------------------------------------------------------

-- Enable RLS on all tables to secure client database requests
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- A. Users RLS Policies
DROP POLICY IF EXISTS "Allow authenticated users read-access to user profiles" ON users;
CREATE POLICY "Allow authenticated users read-access to user profiles" 
ON users FOR SELECT 
TO authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow users to modify their own profile data" ON users;
CREATE POLICY "Allow users to modify their own profile data" 
ON users FOR UPDATE 
TO authenticated 
USING (auth.jwt()->>'email' = email);

DROP POLICY IF EXISTS "Allow users to insert their own profile data" ON users;
CREATE POLICY "Allow users to insert their own profile data" 
ON users FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- B. Contacts RLS Policies
DROP POLICY IF EXISTS "Allow authenticated users to read contacts" ON contacts;
CREATE POLICY "Allow authenticated users to read contacts" 
ON contacts FOR SELECT 
TO authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to create/update contacts" ON contacts;
CREATE POLICY "Allow authenticated users to create/update contacts" 
ON contacts FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);

-- C. Messages RLS Policies
DROP POLICY IF EXISTS "Allow authenticated users to read chat history" ON messages;
CREATE POLICY "Allow authenticated users to read chat history" 
ON messages FOR SELECT 
TO authenticated 
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to send messages" ON messages;
CREATE POLICY "Allow authenticated users to send messages" 
ON messages FOR INSERT 
TO authenticated 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow message senders to add reactions, edit or delete" ON messages;
CREATE POLICY "Allow message senders to add reactions, edit or delete" 
ON messages FOR UPDATE 
TO authenticated 
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow message senders to delete messages" ON messages;
CREATE POLICY "Allow message senders to delete messages" 
ON messages FOR DELETE 
TO authenticated 
USING (true);

-- -------------------------------------------------------------
-- 6. SYSTEM INITIALIZATION DATA (Zero-knowledge System Contact)
-- -------------------------------------------------------------

-- Seed default global self-chat me contact record
INSERT INTO contacts (id, name, "avatarUrl", "isActive", "lastActiveText", "isRecent", "recentMessageText", "recentMessageTime", "recentMessageIsUnread", "isGroup", "isPinned", "description")
VALUES (
  'me',
  'You (Message Yourself)',
  '',
  true,
  'Online',
  true,
  'Tap to send notes, reminders, or drafts to yourself.',
  '',
  false,
  false,
  true,
  'Your personal notes and reminders container. Encrypted and synced.'
)
ON CONFLICT (id) DO NOTHING;
